spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainticket?serverTimezone=GMT%2B8 # 驱动类型：协议：//ip地址：端口号/数据库名称?参数（不使用ssl连接）
    username: root
    password: 19971204d
    driver-class-name: com.mysql.cj.jdbc.Driver #jdbc驱动名称
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      timeout: 900s #一次会话有效时间

